name: Debug
on:
  push:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true # prevent the workflow to fail if this job fails
    steps:
    - run: curl -L https://packagecloud.io/cloudamqp/lavinmq/gpgkey | sudo apt-key add -
      shell: bash
      continue-on-error: true
    - run: echo "deb https://packagecloud.io/cloudamqp/lavinmq/ubuntu/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/lavinmq.list
      shell: bash
      continue-on-error: true
    - run: sudo apt-get update
      shell: bash
      continue-on-error: true
    - run: sudo apt install lavinmq
      shell: bash
      continue-on-error: true
    - run: sudo ls -al /etc/lavinmq
      shell: bash
      continue-on-error: true
    - run: sudo cat /etc/lavinmq/lavinmq.ini
      shell: bash
      continue-on-error: true
    - run: sudo systemctl start lavinmq.service
      shell: bash
      continue-on-error: true
    - run: sudo systemctl status lavinmq.service
      shell: bash
      continue-on-error: true