name: Test this action
on:
  pull_request:
  push:
    branches-ignore:
    - v1
    paths-ignore:
    - README.md
  schedule:
    - cron:  "0 6 * * 6" # 06:00 every Saturday
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
        version:
          - latest

    name: ${{ matrix.os }} (${{ matrix.version }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - uses: ./
      with:
        version: ${{ matrix.version }}
    - run: lavinmq --version
    - run: systemctl is-active lavinmq.service
    - run: echo $AMQP_URL
