name: Test this action
on:
  pull_request:
  push:
    branches-ignore:
    - v1
    paths-ignore:
    - README.md
  schedule:
    - cron:  "0 6 * * 6" # 06:00 every Saturday
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./
    - run: lavinmq --version
    - run: systemctl is-active lavinmq.service
    - run: echo $AMQP_URL
